### ISSUE TITLE
Update that GenAIExamples main docs to list all the existing examples

### ISSUE THREAD

**Issue by mkbhanda** [opea-project/docs#115]
Currently lists 9 as opposed to all 14

**Comment by dbkinder** [comment]
Check out https://opea-project.github.io/latest/examples/index.html#agentqna-application

**Comment by mkbhanda** [comment]
@dbkinder -- where is the source for this if one wants to edit?
GitHub cave dweller asking!

**Comment by dbkinder** [comment]
At the top of the GitHub.io page you'll see a link to "view page source". The last part of the url will let you know where the source is (ignore the .txt at the end). This page's source is in the docs repo /examples/index.rst. If the content was from one of the other repos, you'd see something like GenAIExamples/AgentQnA/retrieval_tool/README.md. 

BTW, the titles of the documents listed on this Examples page are pulled from the title heading in each document, so if you don't like the title shown, you'd fix it in that document.
