### ISSUE TITLE
Create Issue Templates for the docs Repo

### ISSUE THREAD

**Issue by kdruckman** [opea-project/docs#186]
The opea-project/GenAIExamples repo has issue templates in place for bug reports and feature requests. Similar templates would be helpful here as well. 

GitHub documentation on how to do this: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by SachinVarghese** [comment]
Nice idea, I am happy to set this up. Can you please add me as a maintainer on the org?

**Comment by chickenrae** [comment]
Assigned you!!!!!

**Comment by SachinVarghese** [comment]
Created a pull request #201
