### ISSUE TITLE
doc: RFC Archive title typo

### ISSUE THREAD

**Issue by minchene** [opea-project/docs#19]
The title of this document https://github.com/opea-project/docs/blob/main/community/rfcs/README.md has a minor spelling error or typo. It displays "RFC Archieve" and should be "RFC Archive". Low priority fix but customer facing visible. Thanks!

**Comment by ftian1** [comment]
many thanks for your kind reminder. it's weird why preci doc spelling check tool doesn't raise such issue. we will double check and fix it.
