### ISSUE TITLE
Docker install instructions under ChatQnA versus a common place

### ISSUE THREAD

**Issue by mkbhanda** [opea-project/docs#213]
Docker is necessary for both building container images and for running it in a single node docker environment. We need to move it an expected place, that is common to all our build and run usages.
Currently it is under GenAIExamples/ChatQnA/docker_compose/install_docker.sh
Perhaps under GenAIInfra?

**Comment by preethivenkatesh** [comment]
Malini, Can you please move this ticket to genaiexamples? This is not docs feature/req :)
