### ISSUE TITLE
Amazon EKS instructions

### ISSUE THREAD

**Issue by arun-gupta** [opea-project/docs#261]
Amazon recommends their customers to create an EKS cluster using https://www.eksworkshop.com/. Can we replace the [instructions](https://opea-project.github.io/latest/guide/installation/k8s_install/k8s_instal_aws_eks.html) with that link instead?

**Comment by yinghu5** [comment]
Hi Arun, 
As the link https://www.eksworkshop.com/ seems a workshop from Amazon, i add it along with Youtube video guide and get start guide. 
thanks
