### ISSUE TITLE
doc: framework.md figures are missing

### ISSUE THREAD

**Issue by dbkinder** [opea-project/docs#44]
The framework.md document has captions for figures, but all the figures are missing.  Where can these figure images be found and included into this document?

@arun-gupta I see your issue #3 asked for this framework.md to be created from a document link that now does not exist.  Are the images in a word doc somewhere?

**Comment by arun-gupta** [comment]
The text document did not have any images and #3 was just converting the text to markdown. The Word doc exists at https://github.com/opea-project/docs/blob/main/OPEA%20-%20Rev05%20PS%20-%204_15_2024.docx and does have all the images.
