### ISSUE TITLE
Tag this docs repo for releases

### ISSUE THREAD

**Issue by dbkinder** [opea-project/docs#73]
When a release is made, each of the GenAI* repos is tagged. The docs repo must also be tagged at the same time.

**Comment by dbkinder** [comment]
@kding1 @mkbhanda We need the docs repo tagged along with the GenAI* repos when we do a release.

**Comment by mkbhanda** [comment]
@chensuyue @hshen14 please help.

**Comment by chensuyue** [comment]
Ok, will do.

**Comment by chensuyue** [comment]
https://github.com/opea-project/docs/tree/v0.9, will create tags together with source code release in the future.
