### ISSUE TITLE
rst file shown versus displayed, requires an additional click

### ISSUE THREAD

**Issue by mkbhanda** [opea-project/docs#82]
When navigating to the getting started guide link to index.rst is displayed versus its content.
Likewise for GMC install etc. Would this flow be simplified?

**Comment by mkbhanda** [comment]
Follow link https://github.com/opea-project/docs/tree/main/getting-started
it shows index.rst  file instead of displaying the contents of index.rst.
I certainly can click on the file link but was wondering if that is a bug

**Comment by dbkinder** [comment]
We're encouraging folks to read the OPEA documentation at https://opea-project.github.io and not directly from github.com.
