### ISSUE TITLE
Simplify OPEA introduction

### ISSUE THREAD

**Issue by mkbhanda** [opea-project/docs#83]
On https://github.com/opea-project/docs
did we mean "sits" versus "sites" for where OPEA is situated in LF Data and AI?

We could simplify these two items

s/Detailed framework of composable/Composable

s/Architectural blueprints of retrieval-augmented generative AI component stack structure, and end-to-end workflows/Architectural blueprints of retrieval-augmented generative AI end-to-end workflows

**Comment by dbkinder** [comment]
- _did we mean "sits" versus "sites" for where OPEA is situated in LF Data and AI?_
  No.  It's a list of sites

The other suggestions are fine.

**Comment by dbkinder** [comment]
Done.
